// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvefwotpjzjigthzsarh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2ZWZ3b3RwanpqaWd0aHpzYXJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMTQ2NDAsImV4cCI6MjA2NjU5MDY0MH0.G-Cx10LkCXZArNjY42v82VK4o1YfCWT5Jgy18BjGSPg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});